---
- name: Install HAProxy
  yum: name=haproxy
- name: Configure HAProxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: reload haproxy
- name: Enable HAProxy on boot and start service
  service: name=haproxy enabled=yes state=started
